# Q1 - 7*7 matrix with values ranging from 0-6

In [11]:
import numpy as np
print(np.broadcast_to(np.arange(0, 7, dtype=int), (7,7)))

[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


# 7*7 Martrix with random values in range 0-6

In [12]:
#np.random.random_integers(0,7, size=(7,7))

# Q2

In [13]:
#Solution 1
from numpy.lib.stride_tricks import sliding_window_view, as_strided
sliding_window_view(np.arange(4,36,4), 3)

array([[ 4,  8, 12],
       [ 8, 12, 16],
       [12, 16, 20],
       [16, 20, 24],
       [20, 24, 28],
       [24, 28, 32]])

In [14]:
#Solution 2:
as_strided(np.arange(4,36,4), shape=(6, 3), strides=(8, 8))

array([[ 4,  8, 12],
       [ 8, 12, 16],
       [12, 16, 20],
       [16, 20, 24],
       [20, 24, 28],
       [24, 28, 32]])